name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Print working directory
      run: pwd

    - name: List contents of the project directory
      run: ls -la gabi_makeup


    - name: List directory structure
      run: ls -la

    - name: Navigate to project directory
      run: cd gabi_makeup && pwd

    - name: Install dependencies
      run: npm install --force


    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build
